feat: mesa 24.1 (#1082)
* feat: mesa 24.1

Description of changes:

- Upgrade to mesa 24.1
- Remove Broadcom fix backport since it's part of 24.1 release
- 'nouveau-experimental' vulkan driver is now just 'nouveau'
- disable Intel RayTracing on anything but x86_64 (it's not supported
  anywhere else)
- Few dependency definitions / updates to fix build issues
  - python3-pycparser
  - cbindgen
  - version bump for wayland-protocols
  - restrict proc-macro2 crate to `< 1.0.80` (fixes
    `error[E0658]: use of unstable library feature 'proc_macro_byte_character'`)
    - also restricting syn crate to `< 2.0.59` because of dependency conflict
      on proc-macro2
  - add 'paste' crate
- add new dri libs to defined output files

* update to rc3

* 1.0.79 seemed to work previously; try that

It worked here:
https://copr.fedorainfracloud.org/coprs/trouter/bazzite-multilib/build/7337624/

Which was a build from the 'main' branch of mesa before
they released the first RC of 24.1

* Revert "1.0.79 seemed to work previously; try that"

This reverts commit 4f52e2dda394bde7a3c450c20b1e6c736558dbd5.

* rust 1.78 is in F40 now which might fix this?

* revert syn package restriction; should be fixed now rust 1.78 is here

* attempt to fix build; make sacrifice to meson gods

* bump to rc4

* chore: Update to stable 24.1.0

---------

Co-authored-by: Kyle Gospodnetich <me@kylegospodneti.ch>